flips:
  outputs:
    dev:
      type: duckdb
      path: duck_db_files/flips.db
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: eu-west-2
        s3_access_key_id: "{{ env_var('S3_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('S3_SECRET_ACCESS_KEY') }}"
  target: dev